name: Auto School Schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install requests pdfplumber beautifulsoup4

      - name: Run Scraper
        run: python scraper.py

      - name: Save Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # This line ensures we don't crash if the file is missing
          git add professors.txt || echo "No file found to add"
          git commit -m "AI automated update" || exit 0
          git push
